name: Update Version and Create PR

on:
  push:
    tags:
      - v*

jobs:
  update-version-and-create-pr:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Get New Branch and Tag
        id: tag
        run: |
          tag=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/tags | jq -r .[0].name)
          branch="rc/$tag"
          # branches=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/branches" | jq -r '.[].name')

          # echo "TAG_NAME=$tag" >> "$GITHUB_OUTPUT"

          # IFS='.' read -ra max_version <<< "0.0.0"
          # for branch in $branches; do
          #   if [[ $branch == rc/v* ]]; then
          #     version=$(echo $branch | sed -E 's/rc\/v([0-9]+(.*)[0-9]+)/\1/')
          #     IFS='.' read -ra version_numbers <<< "$version"

          #     if (( ${version_numbers[1]} > ${max_version[1]} )); then
          #       max_version=(${version_numbers[@]})
          #       max_version_branch=$branch

          #     elif (( ${version_numbers[2]} > ${max_version[2]} )); then
          #       max_version=(${version_numbers[@]})
          #       max_version_branch=$branch

          #     elif [ "${version_numbers[3]+exist}" ]; then
          #       if [ "${max_version[3]+exist}" ]; then
          #         if (( ${version_numbers[3]} > ${max_version[3]} )); then
          #           max_version=(${version_numbers[@]})
          #           max_version_branch=$branch
          #         fi
          #       else
          #         max_version=(${version_numbers[@]})
          #         max_version_branch=$branch
          #       fi
          #     fi
          #   fi
          # done

          echo "BRANCH_NAME=$branch" >> "$GITHUB_OUTPUT"

      - name: Checkout repository2
        uses: actions/checkout@v3
        with:
          ref: ${{steps.tag.outputs.BRANCH_NAME}}

      - name: Commit and push changes
        run: |
          sed -i "s/__version__ =.*/__version__ = '${{steps.tag.outputs.TAG_NAME}}'/" ros2caret/__version__.py
          git add ros2caret/__version__.py
          git commit -m "chore: update version to ${{ steps.tag.outputs.TAG_NAME }}" -s
          git push origin ${{steps.tag.outputs.BRANCH_NAME}}

      - name: Re-create tag
        run: |
          git push -d origin ${{ steps.tag.outputs.TAG_NAME }}
          git tag ${{ steps.tag.outputs.TAG_NAME }}
          git push origin ${{ steps.tag.outputs.TAG_NAME }}

      - name: Create PR to main branch
        run: |
          gh pr create --title "chore: update version to ${{ steps.tag.outputs.TAG_NAME }}" \
                       --body "This pull request updates the version in __version__.py to ${{ steps.tag.outputs.TAG_NAME }}" \
                       --base main \
                       --head ${{ steps.tag.outputs.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
